# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8d1aa8573623247558586283e246518f02557c546715de3f0d040562054fcf4d73a0640ca1bbd61f362afdd7439b090154f91c565dd325542edcf401db9c676

test:
  secret_key_base: aa47db20b217b658409c5629d348d7a4b6d2bf3a43eb40d883725268e34199fe29c9f384538434295dc19da044494cad4d68e82a409dd1ff128a9549cabf91a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
